### ISSUE TITLE
Add Coind SSL Support

### ISSUE THREAD

**Issue by baitnfatty** [Crypto-Expert/stratum-mining#149]
You seemed to have not put in an option for SSL in your default config. 

Why is this? 

Is it because you implemented in the stratum proxy? 

I am currently trying to get SSL working with the values of:

SSL_PRIVKEY = 'server.key'
SSL_CACERT = 'server.crt'

No dice. 

without SSL everything works fine. im just wondering as to why this functionality is not in the config? 

By the way thanks for all your work! Glad to see someone going in this direction!

**Comment by ahmedbodi** [comment]
refactor done here: https://github.com/Multicoin-co/stratum-mining/pull/2 now you can specify your own diff1 and algo and SSL

**Comment by baitnfatty** [comment]
Hahah nice work ahmedbodi!!! Too bad the cryptos are about dead.

**Comment by ahmedbodi** [comment]
yep i know :)
