### ISSUE TITLE
Manual per worker diff

### ISSUE THREAD

**Issue by nicoschtein** [Crypto-Expert/stratum-mining#32]
Let say we have a new table

    --------------------------------------------
    worker_id    |    diff    |    enabled
    --------------------------------------------

Mpos will add a row for each worker.
Stratum will first look in that table if there is a row for a worker, if there is, use that diff, if there is not, use vardiff (or whatever stratum is setup to).
Taking into account the `enabled` flag that helps not having to delete each worker's row when someone does not want to use manual diff anymore.

**Comment by ahmedbodi** [comment]
I believe this was done here: https://github.com/Multicoin-co/stratum-mining/pull/2 now you can specify your own diff1 and algo
