### ISSUE TITLE
Adding twisted.internet.defer.DeferredLock() to BitcoinRPC._call()

### ISSUE THREAD

**Issue by tuaris** [Crypto-Expert/stratum-mining#352]
I've come across a problem where the wallet daemon may get DoS'd when a miner is finding valid block very quickly for a low difficulty coin.  I am wondering if anyone has any thoughts on the side effects that may result from implementing the following code changes/additions:

In, "lib/bitcoin_rpc.py":

Add:
```
	def __init__(self, host, port, username, password):
                ...
		self._lock = defer.DeferredLock()
               ...
```
Then change
```
	def _call(self, method, params):
                ...
		return self._lock.run(self._call_raw, json.dumps({
				'jsonrpc': '2.0',
				'method': method,
				'params': params,
				'id': '1',
			}))
```

I am still testing and so far I have not seen any issues.  Any opinions and thoughts would be appreciated.

**Comment by ahmedbodi** [comment]
refactor done here: https://github.com/Multicoin-co/stratum-mining/pull/2 now you can specify your own diff1 and algo
