### ISSUE TITLE
Quark Pool

### ISSUE THREAD

**Issue by bitquarkcoin** [Crypto-Expert/stratum-mining#354]
I'm running a BitQuark MPOS pool. The coin is a quark algorithm. The problem I'm having is miners running GPU's without the "difficulty-multiplier 256" set in their config/bat file are throwing off the hashrate and shares. I've noticed on coinmine.pl Quarkcoin pool he has it setup so that GPU miners without the difficulty multiplier shares are rejected. How can I setup my stratum to reject shares for the rogue GPU miners?

Thanks,
BTQ Dev

**Comment by ahmedbodi** [comment]
refactor done here: https://github.com/Multicoin-co/stratum-mining/pull/2 now you can specify your own diff1 and algo
