### ISSUE TITLE
Cannot open port 3333

### ISSUE THREAD

**Issue by globaltoken** [Crypto-Expert/stratum-mining#365]
Hey,

I got an Error on Debian, I cannot listen on Port 3333 for Mining, I don't know why?
It starts, MPOS Works fine, but cannot connect any Miners to it :(

Whats wrong?

**Comment by ahmedbodi** [comment]
firewall?

**Comment by globaltoken** [comment]
Already got it buddy, there was missing packages :)
Thanks for your help :)

**Comment by globaltoken** [comment]
This issue is closed now
