### ISSUE TITLE
How to use stratum-mining with sha256 (peercoin)?

### ISSUE THREAD

**Issue by zencd** [Crypto-Expert/stratum-mining#370]
Please help me with tuning of `stratum-mining` for use with peercoin, algorithm 'sha256'.

I'd like to set `conf/config.py` ALGO_NAME to a value like 'sha256', but it should be an existing Python module implementing method `getPowHash`, otherwise `lib/template_registry.py` fails to load. So how to find such a module? I've not found such one. Or how to write one by myself?

**Comment by ahmedbodi** [comment]
algo name should be the name of a sha256 module
