### ISSUE TITLE
Bitcoin ALGO

### ISSUE THREAD

**Issue by kevinmitnik** [Crypto-Expert/stratum-mining#372]
Hi there.
Bitcoin use SHA256d (Duble SHA256)

If  ALGO_NAME = 'sha256d' 

```
File "/opt/stratum-mining/lib/template_registry.py", line 6, in <module>
            algolib = __import__(settings.ALGO_NAME)
        exceptions.ImportError: No module named sha256d
```

Where I can find this module?
Or I can use a standard module. Crypto.Hash.SHA256 ?
#
Thankful in advance for the answer.

**Comment by ahmedbodi** [comment]
Need a SHA256 Specific Hashing module which gives a getPoWHash function
