### ISSUE TITLE
CONFIG_VERSION is missing from sample_config.py

### ISSUE THREAD

**Issue by AmazingDreams** [Crypto-Expert/stratum-mining#378]
CONFIG_VERSION is missing from sample_config.py and this causes a crash.

I fixed it by adding the following:

```
#********************* Config Version ***************
CONFIG_VERSION = 0.1
# ******************** BASIC SETTINGS ***************
# These are the MUST BE SET parameters!
```

It would be nice if it was included in the config sample.

**Comment by jlperan** [comment]
How did you solved the crash with the following error?

exceptions.ImportError: No module named lyra2re2_hash

Where are the valid module names?

**Comment by AmazingDreams** [comment]
@jlperan I'm sorry I'm only using scrypt.

I gotta say that it this poorly documented. However you could try:

```
sudo pip install lyra2re_hash
```

If that does not work I don't know how to help you further.

**Comment by Bushstar** [comment]
To fix this I deleted to following from mining/__init__.py as I could not find any other reference to it when grepping. Does it do anything?

    if settings.CONFIG_VERSION == None:
        settings.CONFIG_VERSION = 0
    else: pass

**Comment by ahmedbodi** [comment]
Already been removed. It did have a functionality but that was removed too.
