### ISSUE TITLE
getblocktemplate error

### ISSUE THREAD

**Issue by knkrth** [Crypto-Expert/stratum-mining#379]
Hi, when I run twistd -ny launcher.tac I got the following error,

`2017-09-20 14:08:49,683 INFO mining # Found submitblock
2017-09-20 14:08:49,688 ERROR mining # Coind Error: Support for 'segwit' rule requires explicit client support`

Can you help me to solve this issue?

**Comment by Bushstar** [comment]
I've updated Stratum for SegWit though be warned my stratum needs to be restarted roughly every three days. Currently trying to get to the bottom of it but it is at least updated for SegWit and removes getwork.

https://github.com/Bushstar/stratum-mining/commits/master

**Comment by knkrth** [comment]
Thank you. I just use NOMP as Stratum.
