### ISSUE TITLE
Multiple instances of stratum-mining

### ISSUE THREAD

**Issue by Bushstar** [Crypto-Expert/stratum-mining#383]
We have users of different hash power from CPU to farms, to  cater for all we set up multiple instance of stratum-mining with lowest difficulty of 32, 256, 512 and 1024, these are all copies of the 32 diff set up and point to the same database and coin daemon but are available on different ports.

Is this the correct way to support different difficulties on one pool or will we end up with issues?

I ask as the pool has been paying multiple pool bonuses to people.

**Comment by ahmedbodi** [comment]
Yea afaik

Sent from my iPhone

On 13 Oct 2017, at 12:55, Peter Bushnell <notifications@github.com<mailto:notifications@github.com>> wrote:


We have users of different hash power from CPU to farms, to cater for all we set up multiple instance of stratum-mining with lowest difficulty of 32, 256, 512 and 1024, these are all copies of the 32 diff set up and point to the same database and coin daemon but are available on different ports.

Is this the correct way to support different difficulties on one pool or will we end up with issues?

I ask as the pool has been paying multiple pool bonuses to people.
