### ISSUE TITLE
1024 difficulty

### ISSUE THREAD

**Issue by Bushstar** [Crypto-Expert/stratum-mining#387]
The maximum difficulty seems to be 1024, var diff never goes higher than this and if I try to set it higher manually miners connect at a difficulty of 0 and it logs as fake. There are single ASICs where 1024 is too low, mining with 256MH Scrypt against stratum running 1024 I'm only getting about 33% performance.

**Comment by ahmedbodi** [comment]
Should be able to. I've used it higher than that
