### ISSUE TITLE
Only able to use 1 worker

### ISSUE THREAD

**Issue by ampbuster** [Crypto-Expert/stratum-mining#49]
I have a very strange problem.

If I use more than 1 worker for mining at this pool that I set up (using this stratum software), all other workers will get REJECTED: (-2, u"Job 'xxx' not found", None) error.

If one worker has submitted a share for a certain job, that worker will be able to continue submitting shares, but shares from all my other workers will get rejected.

This continues until the next block where only the first worker to submit a share is able to continue submitting shares.

Does anyone have a solution for this problem?

**Comment by ed-ro0t** [comment]
@ampbuster: here's a workaround...
increase the duration for jobs in [**work_log_pruner.py**](https://github.com/Crypto-Expert/stratum-mining/blob/master/mining/work_log_pruner.py#L12)   `if now > userwork[wli][2] + 120`
