### ISSUE TITLE
 ERROR block_updater # UpdateWatchdog.run failed

### ISSUE THREAD

**Issue by jinpeng309** [Crypto-Expert/stratum-mining#68]
I want to build a JKC Pool(https://github.com/Hartland/JKC) , but when I run the twisted get the error message like below:
2013-12-28 23:16:51,888 ERROR block_updater # UpdateWatchdog.run failed
Traceback (most recent call last):
  File "/root/stratum-mining/lib/block_updater.py", line 49, in run
    prevhash = util.reverse_hash((yield self.bitcoin_rpc.prevhash()))
Error: 500 Internal Server Error
My junkcoin.conf like below:

noirc=1
rpcuser=name
rpcpassword=123456
rpcallowip=*
port=19333
rpcport=9772
gen=0
4way=1

**Comment by erm3nda** [comment]
I have a similar issue, but `Error: 404 Not Found`
@Hartland , by "I believe you are getting the error because you are not connecting to anybody, let alone building the block chain." did you meant to addnodes?

I tried adding 2 from supernodes list, but didn't work.
